---

- block:

    - set_fact:
        sdteams_message: "{{ teams_error_message }}"
        sdteams_details: |
            Error occured in task:
                
                {{ ansible_failed_task.name | replace('"','') |replace("'","") | regex_replace('[}{]','') }}
            
            Error message was:

            {{ ansible_failed_result.msg | replace('"','') |replace("'","") | regex_replace('[}{]','') }}

    - include_tasks: "{{ sdteams_role_path }}/handlers/main.yml"
  
    - fail:
        msg: "{{ sdteams_details }}"

  when: sdteams_status == "failure"

- block:

    - include_tasks: "{{ sdteams_role_path }}/handlers/main.yml"

  when: sdteams_status == "success"
